version: '3.2'
services:
  server:
    env_file:
      - ./.env
    environment:
      - NODE_DATABASE_URL=mongodb://mongo:27017
    build: ./
    working_dir: /vendor-api
    volumes:
      - ./:/vendor-api/
      - /vendor-api/node_modules
    command: bash -c "npm i && npm start"
    depends_on:
      - mongo
    ports:
      - '${NODE_PORT}:${NODE_PORT}'
  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongodata:/data/db

volumes:
  mongodata:
    driver: local
