# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Vendor API Merge master

on:
  push:
    branches: [master]


jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      working-directory: /var/www/vendorApi

      - run: git checkout .
      - run: git pull
      - run: npm ci
      - run: npm test
      - run: pm2 restart all

    env:
      NODE_ENV: deploy
      AUTH_SECRET: aSuperSecret4testing
