# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Vendor API CI

on:
  push:
    branches: [master]
  # pull_request:
  #   branches: [ master ]

jobs:
  build:
    runs-on: self-hosted
    #runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: git checkout .
      - run: git pull
      - run: npm ci
      - run: npm test
      - run: pm2 restart all

    env:
      NODE_ENV: deploy
      AUTH_SECRET: aSuperSecret4testing
